---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: "${CLUSTER_NAME}"
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.45.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.46.0.0/16
  topology:
    class: rke2-class
    version: ${KUBERNETES_VERSION}+rke2r1
    controlPlane:
      metadata: {}
      replicas: ${CABPR_CP_REPLICAS}
    workers:
      machineDeployments:
      - class: default-worker
        name: md-0
        replicas: ${CABPR_WK_REPLICAS}
    variables:
      - name: dockerKindImage
        value: kindest/node:${KUBERNETES_VERSION}

