---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereMachineTemplate
metadata:
  name: vsphere-controlplane
  namespace: ${CABPR_NAMESPACE}
spec:
  template:
    spec:
      cloneMode: linkedClone
      datacenter: ${CABPR_VCENTER_DATACENTER}
      datastore: ${CABPR_VCENTER_DATASTORE}
      diskGiB: ${CABPR_VCENTER_DISKSIZE}
      folder: ${CABPR_VCENTER_FOLDER}
      memoryMiB: ${CABPR_VCENTER_VM_MEMORY}
      network:
        devices:
        - dhcp4: true
          networkName: ${CABPR_VCENTER_NETWORK}
      numCPUs: ${CABPR_VCENTER_VM_VPCU}
      os: Linux
      resourcePool: "${CABPR_VCENTER_RESOURCEPOOL}"
      server: ${CABPR_VCENTER_HOSTNAME}
      storagePolicyName: ""
      template: ${CABPR_VCENTER_VM_TEMPLATE}
      thumbprint: ${CABPR_VCENTER_THUMBPRINT}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereMachineTemplate
metadata:
  name: vsphere-worker
  namespace: ${CABPR_NAMESPACE}
spec:
  template:
    spec:
      cloneMode: linkedClone
      datacenter: ${CABPR_VCENTER_DATACENTER}
      datastore: ${CABPR_VCENTER_DATASTORE}
      diskGiB: ${CABPR_VCENTER_DISKSIZE}
      folder: ${CABPR_VCENTER_FOLDER}
      memoryMiB: ${CABPR_VCENTER_VM_MEMORY}
      network:
        devices:
        - dhcp4: true
          networkName: ${CABPR_VCENTER_NETWORK}
      numCPUs: ${CABPR_VCENTER_VM_VPCU}
      os: Linux
      resourcePool: "${CABPR_VCENTER_RESOURCEPOOL}"
      server: ${CABPR_VCENTER_HOSTNAME}
      storagePolicyName: ""
      template: ${CABPR_VCENTER_VM_TEMPLATE}
      thumbprint: ${CABPR_VCENTER_THUMBPRINT}