name: run ci checks

on: [pull_request, workflow_dispatch, merge_group]

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true
      - name: Verify
        run: make verify
      - name: Build
        run: make managers
      - name: Test
        run: make test
