name: E2E tests
on:
  pull_request:
  merge_group:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: runs-on,runner=4cpu-linux-x64,run-id=${{ github.run_id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
      - name: Setup kind
        uses: helm/kind-action@v1.12.0
        with:
          install_only: true
      - name: Run E2E tests
        run: make test-e2e
      - name: Archive artifacts
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: e2e-artifacts
          path: _artifacts
          if-no-files-found: ignore
